<?php
/***************************************************************************************
 * Register custom field type
 **************************************************************************************/
function outdoor_acf_include_fields() {
    require_once( OUTDOOR_INC_DIR . '/admin/acf-fields/small-icons.php' );
    require_once( OUTDOOR_INC_DIR . '/admin/acf-fields/social-buttons.php' );
}
add_action('acf/include_field_types', 'outdoor_acf_include_fields');

/***************************************************************************************
 * Settings a fields
 **************************************************************************************/
if( function_exists('register_field_group') ):

    // Register group page settings
    register_field_group(array (
        'key' => 'group_5551a8b64cecf',
        'title' => 'Page settings',
        'fields' => array (
            array (
                'key' => 'field_5551a8d762935',
                'label' => 'Page layout',
                'name' => 'page_layout',
                'prefix' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array (
                    'container' => 'container',
                    'full-width' => 'full-width',
                ),
                'default_value' => array (
                    'container' => 'container',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'disabled' => 0,
                'readonly' => 0,
            ),
            array (
                'key' => 'field_5576b3d1d1d30',
                'label' => 'Invert elements',
                'name' => 'invert_elements',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5551ea4635480',
                'label' => 'Padding top',
                'name' => 'padding_top',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Default: 100px',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5551ea7435481',
                'label' => 'Padding bottom',
                'name' => 'padding_bottom',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Default: 100px',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5551b8bade6c3',
                'label' => 'Height',
                'name' => 'height',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Set the page height. Ex: \'500px\'',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5554a80071f89',
                'label' => 'Show border',
                'name' => 'show_border',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => 'Show the top and bottom border',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5551ec08d0237',
                'label' => 'Video background',
                'name' => 'video_background',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => 'Enable video background',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5551ef1d6dd21',
                'label' => 'Video (.mp4)',
                'name' => 'video_mp4_url',
                'prefix' => '',
                'type' => 'file',
                'instructions' => 'Upload the video file',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551ec08d0237',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_557833e26bb51',
                'label' => 'Video (.ogg)',
                'name' => 'video_ogg_url',
                'prefix' => '',
                'type' => 'file',
                'instructions' => 'Upload the video file',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551ec08d0237',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_557834096bb52',
                'label' => 'Video (.webm)',
                'name' => 'video_webm_url',
                'prefix' => '',
                'type' => 'file',
                'instructions' => 'Upload the video file',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551ec08d0237',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_5551ec34d0238',
                'label' => 'Video autoplay',
                'name' => 'video_autoplay',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => 'Autoplay the video after load page',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551ec08d0237',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
            ),
            array (
                'key' => 'field_5551ed24d0239',
                'label' => 'Video loop',
                'name' => 'video_loop',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551ec08d0237',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
            ),
            array (
                'key' => 'field_5551eea0d023a',
                'label' => 'Video audio mute',
                'name' => 'video_muted',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551ec08d0237',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
            ),
            array (
                'key' => 'field_5551ac006f153',
                'label' => 'Background color',
                'name' => 'bg_color',
                'prefix' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_5551b740f7aed',
                'label' => 'Background image',
                'name' => 'bg_image',
                'prefix' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_5551e549668d5',
                'label' => 'Parallax',
                'name' => 'parallax',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5551e577668d6',
                'label' => 'Parallax speed',
                'name' => 'parallax_speed',
                'prefix' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551e549668d5',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 5,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5551b9f227f99',
                'label' => 'Show overlay',
                'name' => 'show_overlay',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => 'Show the page overlay',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5551ba5627f9a',
                'label' => 'Overlay color',
                'name' => 'overlay_color',
                'prefix' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551b9f227f99',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_5551ba6f27f9b',
                'label' => 'Overlay opacity',
                'name' => 'overlay_opacity',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Set the overlay opacity from 0 to 1. Ex: \'0.95\'',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5551b9f227f99',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '0.95',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5551c487413b8',
                'label' => 'Page title',
                'name' => 'page_title',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5551c00071fd6',
                'label' => 'Title size',
                'name' => 'title_size',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Set the page title size. Ex: \'7.5em\', \'45px\'',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '7.5em',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5551c06a71fd7',
                'label' => 'Title color',
                'name' => 'title_color',
                'prefix' => '',
                'type' => 'color_picker',
                'instructions' => 'Set the page title color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_5559f3a349c95',
                'label' => 'Title subcolor',
                'name' => 'title_subcolor',
                'prefix' => '',
                'type' => 'color_picker',
                'instructions' => 'Set the page title subcolor',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_5551c30c07dc0',
                'label' => 'Title weight',
                'name' => 'title_weight',
                'prefix' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array (
                    100 => 100,
                    200 => 200,
                    300 => 300,
                    400 => 400,
                    600 => 600,
                    700 => 700,
                    800 => 800,
                    900 => 900,
                ),
                'default_value' => array (
                    0 => 800,
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'disabled' => 0,
                'readonly' => 0,
            ),
            array (
                'key' => 'field_55530d043c0e0',
                'label' => 'Text color',
                'name' => 'text_color',
                'prefix' => '',
                'type' => 'color_picker',
                'instructions' => 'Set the page text color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    // Register group portfolio settings
    register_field_group(array (
        'key' => 'group_5552075c5b862',
        'title' => 'Portfolio settings',
        'fields' => array (
            array (
                'key' => 'field_5552076509883',
                'label' => 'Client',
                'name' => 'client',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5552077409884',
                'label' => 'Link',
                'name' => 'link',
                'prefix' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array (
                'key' => 'field_5552078009885',
                'label' => 'Gallery',
                'name' => 'gallery',
                'prefix' => '',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'od-portfolio',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    // Register group pricing settings
    register_field_group(array (
        'key' => 'group_55531949ea68d',
        'title' => 'Price settings',
        'fields' => array (
            array (
                'key' => 'field_555332d1242b0',
                'label' => 'Background color',
                'name' => 'bg_color',
                'prefix' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_555332eb242b1',
                'label' => 'Background opacity',
                'name' => 'bg_opacity',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Ex: \'0.95\'',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '0.95',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_55681886dbdf1',
                'label' => 'Icon',
                'name' => 'icon',
                'prefix' => '',
                'type' => 'small_icon',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'icon_name' => '',
            ),
            array (
                'key' => 'field_555319578a62b',
                'label' => 'Color',
                'name' => 'color',
                'prefix' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#9eb533',
            ),
            array (
                'key' => 'field_555319868a62c',
                'label' => 'Price',
                'name' => 'price',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Ex: \'$100\'',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_555319cf8a62d',
                'label' => 'Price label',
                'name' => 'price_label',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Ex: \'permonth\'',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'permonth',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_55531a0c8a62e',
                'label' => 'Button text',
                'name' => 'text_btn',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Join now',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_55681801cde8b',
                'label' => 'Link',
                'name' => 'link',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_55531a348a62f',
                'label' => 'Features',
                'name' => 'features',
                'prefix' => '',
                'type' => 'repeater',
                'instructions' => 'Add features for the price',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'layout' => 'row',
                'button_label' => 'Add feature',
                'sub_fields' => array (
                    array (
                        'key' => 'field_55531aa38a630',
                        'label' => 'Label',
                        'name' => 'label',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'od-pricetable',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'custom_fields',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'author',
            8 => 'format',
            9 => 'featured_image',
            10 => 'categories',
            11 => 'tags',
            12 => 'send-trackbacks',
        ),
    ));

    // Register group service settings
    register_field_group(array (
        'key' => 'group_55534db9f2af3',
        'title' => 'Service settings',
        'fields' => array (
            array (
                'key' => 'field_55534dc1511a6',
                'label' => 'Icon',
                'name' => 'icon_name',
                'prefix' => '',
                'type' => 'small_icon',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'icon_name' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'od-service',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    // Register group team settings
    register_field_group(array (
        'key' => 'group_5555e0752ccf2',
        'title' => 'Person settings',
        'fields' => array (
            array (
                'key' => 'field_5555e08414995',
                'label' => 'Profession',
                'name' => 'profession',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5555e0cb14996',
                'label' => 'E-mail',
                'name' => 'email',
                'prefix' => '',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array (
                'key' => 'field_5555e0da14997',
                'label' => 'Phone',
                'name' => 'phone',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5555e0f214998',
                'label' => 'Skype',
                'name' => 'skype',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5568329d58c32',
                'label' => 'Social buttons',
                'name' => 'social_btns',
                'prefix' => '',
                'type' => 'social_buttons',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'od-team',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'excerpt',
            1 => 'custom_fields',
            2 => 'discussion',
            3 => 'comments',
            4 => 'revisions',
            5 => 'author',
            6 => 'format',
            7 => 'categories',
            8 => 'tags',
            9 => 'send-trackbacks',
        ),
    ));

    // Register group post settings
    register_field_group(array (
        'key' => 'group_5559afe372c92',
        'title' => 'Post settings',
        'fields' => array (
            array (
                'key' => 'field_5559afef5dd36',
                'label' => 'Gallery',
                'name' => 'gallery',
                'prefix' => '',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    // Register group subscriber settings
    register_field_group(array (
        'key' => 'group_555f149750c8a',
        'title' => 'Subscriber info',
        'fields' => array (
            array (
                'key' => 'field_555f14a033ebd',
                'label' => 'E-mail',
                'name' => 'email',
                'prefix' => '',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'od-subscriber',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'custom_fields',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'slug',
            8 => 'author',
            9 => 'format',
            10 => 'page_attributes',
            11 => 'featured_image',
            12 => 'categories',
            13 => 'tags',
            14 => 'send-trackbacks',
        ),
    ));

endif;